### ISSUE TITLE
error on cpIsLogged

### ISSUE THREAD

**Issue by andrearoot** [TheJoin95/Register.it-Dynamic-DNS-Updater#1]
Hi TheJoin95,

I tried to use your Dynamic DNS Updater but I receive this error:

Traceback (most recent call last):
  File "dns.py", line 130, in <module>
    print login(usr,psw)
  File "dns.py", line 31, in login
    isLogged = cookie['cpIsLogged'] == '1LevelLogged'
KeyError: 'cpIsLogged'

I think something was changed on register.it
Can you help me to solve the issue?
Thanks!

**Comment by TheJoin95** [comment]
Hi Andrearoot,

you was right: they changed something.

Before the submit of the login form, they added a script to verify if you are a real user or not.
Then, they also added the Google Recaptcha (v3) validation, to provide more security on the login form.

The actual solution won't work anymore.

A Possible solution is to create a script with a headless browser (crhome, beautiful soup or phantomjs, maybe) because we need to run JS files.

I'm sorry about that.
I need some time to make the script with the previous solution and I still don't know if it will work with the G-Recaptcha or not.

**Comment by andrearoot** [comment]
bad news :(
in the meantime thanks for your reply.

**Comment by TheJoin95** [comment]
Hi Andrearoot,

I made some changes to the repo and I've implemented a new solution using Nodejs.
Can you give it a try?

I tested some functionalities and it's seems working, without any warning by google recaptcha.
Let me know,
thank you

**Comment by andrearoot** [comment]
Hi TheJoin95,
thanks for the update!
I tried to use this new approach, but I get two errors.
The first error, I solved changing my password (with some special characters, like ! , I need to use single quote, but the password doesn't validated with --password='PASSWORD')
The second change somethimes...

I get this error:
Loading login page
Faking user interaction..
Compiling login form data..
Submit login form..
Logged in succesfully
Loading detail page for the domain: DOMAIN
Loading dns advanced page..
(node:7330) UnhandledPromiseRejectionWarning: Error: No node found for selector: .btn.add
    at assert (/opt/Register.it-Dynamic-DNS-Updater/node/node_modules/puppeteer/lib/helper.js:231:11)
    at DOMWorld.click (/opt/Register.it-Dynamic-DNS-Updater/node/node_modules/puppeteer/lib/DOMWorld.js:366:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/opt/Register.it-Dynamic-DNS-Updater/node/node_modules/puppeteer/lib/helper.js:110:27)
    at Page.click (/opt/Register.it-Dynamic-DNS-Updater/node/node_modules/puppeteer/lib/Page.js:988:29)
    at /opt/Register.it-Dynamic-DNS-Updater/node/index.js:165:16
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:7330) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7330) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

or this error:
Loading login page
Faking user interaction..
Compiling login form data..
Submit login form..
Error on submit
Window close

**Comment by TheJoin95** [comment]
Hi Andrea,

can you give me some example of params that you had use to get these errors?
The second error it's seems because of the google recaptcha, sometimes google know that you are not a human and block you.. in that case you need to wait some minutes.

The first error it's really strange, because the button must exist but the script is new and I've tested a few amount of case so it can happen.

**Comment by andrearoot** [comment]
This is what I use:
node index.js --username=USERNAME --password=PASSWORD --domain=dominio.it --name=test.dominio.it --value=1.1.1.1 --ttl=900 --type=A
My nodejs version is v10.15.3

**Comment by TheJoin95** [comment]
I pushed some changes.
Can you run the script with the same params plus the following:` --headless=false --debug`

The debug flag take some screenshot of the page so you can check if the page is correct or not.
The headless flag, if you have a GPU, will show you a crhomium window.

Let me know, thanks

**Comment by andrearoot** [comment]
Hi TheJoin95,

I solved my problem with:
  1. changed ! in the password with another char and sent with --password='PASSWORD' (with the single quote)
  2. set the proxy to use Italian connectivity (added proxy settings in the index.js file)
I tried 2 times without problems.

Thank you for your support!

**Comment by TheJoin95** [comment]
Perfect, I will check the password parameter andò I will add a proxy parameter.
Thank you for your feedback!

If you want you van wacth or star this repo ;)

**Comment by andrearoot** [comment]
Grazie ancora Miki.
Stavo guardando che è proprio Register che fa schifo...se arrivi da
connessioni diverse blocca tutto e devi rifarlo via browser con il
recaptcha.
Forse anche la password con ! basta inserirla nei ' ' , ma devo ancora fare
qualche prova (il problema potrebbe essere legato sempre al cambio di
connessione).
Diciamo che è un interessante approccio anche se troppo delicato causa
Register, sto valutando se crearmi un dns per gestirmeli in maniera agevole.

*Unica cosa che ho notato è che aggiunge il record e non modifica
l'esistente*


Il giorno lun 27 mag 2019 alle ore 12:32 Miki <notifications@github.com> ha
scritto:
